import './globals.css'
import type { Metadata } from 'next'
import { AlbertSans, SpaceMono } from './fonts'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${AlbertSans.variable} ${SpaceMono.variable}`}>
      <body>
        {children}
      </body>
    </html>
  )
}
